version: '2'
services: 
  nodejs:
    image: node:10.15.1
    volumes:
      - ./:/data
<<<<<<< HEAD
    ports: 
       - 3000:3000
    command: bash -c "npm install && npm start --cache /data/.npm"
=======
    working_dir: /data
    env_file: env/.env
    environment:
      - A=$AAAA
      - B=$BBBB
    ports: 
       - 3000:3000
    command: bash -c "npm install && npm start --cache /data/.npm"
>>>>>>> b598d00b82bfb92fc3924da5378b720f7eec024f
