version: '3'
services: 
  nodejs:
    image: node:8
    ports: 
       - 80:3000
    volumes:
        - /opt/relatorios_codiv/.env:/opt/env/.env
    environment:
        - IPAASVERTIGOURL=http://ip172-18-0-76-blddnbe4315g009ttlfg
    command: bash -c "npm install  && node server"
    restart: always 