version: '2'
services: 
  nodejs:
    image: node:10.15.1
    volumes:
      - ./:/data
    working_dir: /data
    ports: 
       - 3000:3000
    command: bash -c "npm install && npm start --cache /data/.npm"
