image: node:10.15.1

stages:
  - build
  - deploy

build:
  tags:
    - docker

  stage: build
  artifacts:
    paths:
      -  target/*.zip 
  script: 
    - npm install && npm ./server.js
  
deploy project:
  tags:
    - docker
  stage: deploy
  script:
    - cd /builds/vertigobr/tjrj/codiv/relatorios-codiv/target
    - curl -F filetoupload=@/builds/vertigobr/tjrj/codiv/relatorios-codiv/target/relatorios-codiv.zip